--minetest.register_on_mods_loaded(function()
--    minetest.after(15, function()
--        minetest.request_shutdown("normal shutdown", false)
--    end)
--end)

minetest.register_on_joinplayer(function(player)
	local inv = player:get_inventory()
	local item = mcl_enchanting.set_enchantments(ItemStack("pala_armor:helmet_paladium"), {protection = 4, unbreaking = 3})
	--mcl_armor.equip(item, player, true)
	--inv:set_list("armor", {ItemStack(), , enchantments)})
	inv:set_stack("armor", 2, item)
end)